spring:
  datasource:
    username: "root"
    password: "04051995"
    url: jdbc:mysql://localhost:3306/library?useUnicode=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  # V(version)__description.sql
  flyway:
    baseline-on-migrate: true
  mvc:
    format:
      date: yyyy-MM-dd
#      date-time: yyyy-MM-dd HH:mm:ss
#      time: HH:mm:ss
#  jackson:
#    time-zone: Etc/GMT-3

jwt:
  secret: test
  expired: 1